server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ktpm_db
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: payment_schema
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8089
    consumer:
      group-id: payment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8089
        specific.avro.reader: true

vnpay:
  version: "2.1.0"
  command: "pay"
  tmn-code: "W3NRP17R"
  hash-secret: "58E1ELSWK3B2US8U5T6FKBYZGI9603LD"
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "https://google.com"
  ipn-url: "https://corporeal-orlando-incongruously.ngrok-free.dev/api/payments/vnpay/callback"
  ip-addr: "118.70.17.89"
  expire-minutes: 15
  locale: "vn"

# Optional: Logging
logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
