spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ktpm_db
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: payment_schema
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

vnpay:
  version: "2.1.0"
  command: "pay"
  tmn-code: "W3NRP17R"
  hash-secret: "58E1ELSWK3B2US8U5T6FKBYZGI9603LD"
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "https://google.com"
  ipn-url: "https://google.com"
  ip-addr: "127.0.0.1"
  expire-minutes: 15
  locale: "vn"

  # -------------------------
  # Kafka + Avro
  # -------------------------
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

# Optional: Logging
logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    com.example.paymentservice: DEBUG
